CREATE DATABASE earth_development;
USE earth_development;

CREATE TABLE USER_INFO (
  ID                 INT PRIMARY KEY AUTO_INCREMENT,
  USERID             VARCHAR(20) UNIQUE NOT NULL,
  NAME               VARCHAR(50)        NOT NULL,
  GENDER             VARCHAR(1)         NOT NULL,
  CELL_PHONE         VARCHAR(50),
  EMAIL              VARCHAR(50),
  ADDRESS            VARCHAR(100),
  CREATED_TIME       DATETIME           NOT NULL,
  LAST_MODIFIED_TIME DATETIME           NOT NULL
);

CREATE TABLE USER_ACCOUNT (
  ID       INT PRIMARY KEY AUTO_INCREMENT,
  USERID   VARCHAR(20) UNIQUE NOT NULL,
  PASSOWRD VARCHAR(20)        NOT NULL
);

CREATE TABLE PHOTO (
  ID                 INT PRIMARY KEY AUTO_INCREMENT,
  NAME               VARCHAR(50) NOT NULL,
  SIZE               LONG        NOT NULL,
  MIME_TYPE          VARCHAR(20) NOT NULL,
  ADDRESS            VARCHAR(100),
  OWNERID            VARCHAR(20),
  HEIGHT             INT,
  WIDTH              INT,
  CREATED_TIME       DATETIME    NOT NULL,
  LAST_MODIFIED_TIME DATETIME    NOT NULL
)